### ISSUE TITLE
Cancel Objects non functional in GCode Viewer tab

### ISSUE THREAD

**Issue by kb-** [paukstelis/Octoprint-Cancelobject#64]
The orange dot isn't displayed on objects in my GCode Viewer tab (after loading object or while printing). Nothing happens when using the 3 buttons ("Toggle markers", "Reset objects", "Refresh objects"):

![Capture](https://user-images.githubusercontent.com/2260417/103482599-0498c300-4de2-11eb-9373-efb446fc24d4.JPG)

Objects are listed in Cancel Objects tab tho:
![Capture1](https://user-images.githubusercontent.com/2260417/103482610-11b5b200-4de2-11eb-803b-0fe897a3edfb.JPG)

Object change is detected while printing:
![Capture2](https://user-images.githubusercontent.com/2260417/103482613-15e1cf80-4de2-11eb-8212-d4560b7870f3.JPG)

The GCode has the "printing object" tags:
```
; printing object Socket_flange.stl id:1 copy 0
...
; stop printing object Socket_flange.stl id:1 copy 0
; printing object locking_nut.stl id:0 copy 0
```

[fan_holder-4.zip](https://github.com/paukstelis/Octoprint-Cancelobject/files/5761799/fan_holder-4.zip)

GCode is generated by PrusaSlicer 2.2.0, with the options as listed in the comments at the end of the GCode file.
Cancel Objects 0.4.4

An error shows up in the log:
_

> 2021-01-03 04:33:32,486 - octoprint.plugin.core - ERROR - Error loading plugin cancelobject
> Traceback (most recent call last):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1298, in _import_plugin
>     module = _load_module(module_name, spec)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
>     return imp.load_module(name, f, filename, details)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_cancelobject/__init__.py", line 13, in <module>
>     from flask.ext.login import current_user
> ImportError: No module named ext.login

_
[log.zip](https://github.com/paukstelis/Octoprint-Cancelobject/files/5761835/log.zip)

browser.user_agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
connectivity.connection_check: 8.8.8.8:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1400
env.hardware.ram: 918188032
env.os.bits: 32
env.os.id: linux
env.os.platform: linux2
env.plugins.pi_support.model: Raspberry Pi 3 Model B Plus Rev 1.3
env.plugins.pi_support.octopi_version: 0.15.1
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 9.0.3
env.python.version: 2.7.13
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.2
printer.firmware: Marlin V1; Sprinter/grbl mashup for gen6

**Comment by paukstelis** [comment]
For some reason you do not have the latest version of the plugin. The error that is reported was something that fixed back in July. Have you tried uninstalling the plugin and reinstalling?

**Comment by kb-** [comment]
I did that. The plugin manager offered me 0.4.4. 
At the beginning of the posted log I had 0.4.1; at the end 0.4.4.

**Comment by paukstelis** [comment]
I have not been able to reproduce this. My first thought was that there was something wrong with absolute extrusion and tracking, but it works fine for me. Could you try relative extrusion and see if it makes any difference?

**Comment by paukstelis** [comment]
Your gcode works fine for me, so there must be something else (plugin?) that is causing an issue.

![Screenshot from 2021-01-13 14-48-15](https://user-images.githubusercontent.com/28326982/104503168-bb4d2e00-55ae-11eb-87af-c26eaffb58c5.png)

**Comment by tablatronix** [comment]
Doesn't work for me either. I just uninstalled and reinstalled. The 3 buttons do not appear to do anything..

**Comment by paukstelis** [comment]
First place to look will be in the web browser console. Just to confirm, when you try to use the buttons you do have visible objects that have orange dots on them?

**Comment by tablatronix** [comment]
no dots, no change at all for either of them, checked the console no errors or anything.

**Comment by paukstelis** [comment]
What other plugins do you have installed?

**Comment by paukstelis** [comment]
FYI, there shouldn't be any dots before printing (unless you use SuperSlicer). The dots are done by tracking where extrusions are taking place during the printing of an object.

**Comment by the0bone** [comment]
I just had a similar effect. Printed a Design from Fusion and while I'm with a german version, Fusion names to bodies as "Körper".
The special character ö caused the PlugIn to not understand the different objects.
The Status of current object was always no and the dots did not show up.

After changing the name all is fine.
